[package]
name = "rel"
version = "0.6.0"
authors = ["1011X <1011XXXXX@gmail.com>"]
repository = "https://github.com/1011X/REL-16"
edition = "2018"

readme = "README.md"
license = "0BSD"

[dependencies]
getopts = "0.2.14"

[features]
teleport = []
